name: ci

on:
  push:
    branches:
      - main
      - deprecate-hidden

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "9.8.1"
        os:
        - "macos-latest"
        - "ubuntu-latest"
        - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Compile
        run: cabal build